version: '3.8'

services:
  db:
    image: postgres:15.6
    container_name: db
    volumes:
      - /data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=setorT
      - POSTGRES_USER=setorT
      - POSTGRES_PASSWORD=setorT@2024$
    ports:
      - "5432:5432"
    networks:
      - network

  web:
    container_name: web
    build: 
      context: .
      dockerfile: Dockerfile

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=setorT
      - POSTGRES_USER=setorT
      - POSTGRES_PASSWORD=setorT@2024$
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    driver: bridge
